[package]
name = "seuHealthReport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = {version = "4.0.18"}
reqwest = {version = "0.11.12", features =["json","blocking", "cookies"] }
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
